# Generated by Django 3.0.2 on 2020-01-23 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('avatar', models.ImageField(blank=True, upload_to=user.models.upload_location)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Date of birth')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff access')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin access')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser access')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribing_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscribing',
            field=models.ManyToManyField(related_name='subscribed', through='user.UserSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
